# @generated by `mireye-earth catalog codegen` — DO NOT EDIT BY HAND.
# Source of truth: mireye_earth.ask.catalog.PRESETS. Regenerate after a
# preset change; CI `mireye-earth catalog codegen --check` fails on drift.
from __future__ import annotations

from typing import Literal

MireyePreset = Literal[
    "terrain",
    "flood_risk",
    "wildfire_underwrite",
    "land_cover",
    "site_selection",
    "building_lookup",
    "points_of_interest",
    "utilities",
    "boundaries",
    "solar_siting",
    "wind_siting",
    "storage_siting",
    "data_center_siting",
    "grid_interconnect",
    "natural_hazard",
]

PRESET_NAMES: tuple[str, ...] = tuple(MireyePreset.__args__)
